FROM ubuntu:14.04
MAINTAINER Daniel Oltmanns

# Setup basic environment
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y install apt-transport-https ca-certificates

# add node repo
RUN echo "" >> /etc/apt/sources.list
RUN echo "deb http://deb.nodesource.com/node_5.x trusty main" >> /etc/apt/sources.list

# install requirements
RUN apt-get update && apt-get -y --force-yes install \
  nano \
  vim \
  git \
  curl \
  bash-completion \
  unzip \
  nodejs

# copy src (to start the first time)
RUN mkdir /src
COPY src /src
WORKDIR /src

# install node packages
RUN npm install -g supervisor
RUN npm install -g bower
RUN npm install
RUN bower install --allow-root

EXPOSE 80

# CMD bash
# CMD ["nodejs", "/src/app.js"]
CMD ["supervisor", "/src/app.js"]
