#!/bin/bash

cd ~/code/projects/social-painting

if test $# -eq 0; then
  docker-compose -f docker-compose-dev.yml down
else
  for I in $*; do
    docker-compose -f docker-compose-dev.yml down social-painting-dev-$I
  done
fi

rm -f etc/data/pics/*png
